### ISSUE TITLE
Authorization is not secure

### ISSUE THREAD

**Issue by jordyvanvorselen** [jordyvanvorselen/rib-reviews#15]
Currently the backend has a 'hardcoded' API key that is saved in the Flutter frontend. Someone who reverse engineers the .apk could potentially retrieve the API token. The worst that could happen is someone spam creating events/reviews. 

Proper authorization would guard against this and would be a better solution.

**Comment by pascalw** [comment]
Since you have Google sign in you could verify Google JWT's in your backend. See https://developers.google.com/identity/gsi/web/guides/verify-google-id-token. Then you don't need a hardcoded API key and you can prevent impersonation (no need to pass `user_id`s in the API's).

**Comment by jordyvanvorselen** [comment]
> Since you have Google sign in you could verify Google JWT's in your backend. See https://developers.google.com/identity/gsi/web/guides/verify-google-id-token. Then you don't need a hardcoded API key and you can prevent impersonation (no need to pass `user_id`s in the API's).

Ah nice, looks like an elegant way to solve it using the existing setup. Thanks!
